label variable PUMFID    "Unique household identifier"
label variable EHA_10    "Economic hardship - level of difficulty experienced - past 12 months"
label variable EHA_25    "Economic hardship - skipped/delayed mortgage/rent payment"
label variable FP_05     "Fire Prevention - Working smoke detector"
label variable DWI_05A   "Dwelling issues - mould or mildew"
label variable DWI_05B   "Dwelling issues - pests"
label variable DWI_05C   "Dwelling issues - undrinkable water"
label variable DWI_05D   "Dwelling issues - poor indoor air quality"
label variable NEI_05A   "Neighbourhood issues - noisy neighbours or loud parties"
label variable NEI_05B   "Neighbourhood issues - people hanging around on the streets"
label variable NEI_05C   "Neighbourhood issues - garbage or litter lying around"
label variable NEI_05D   "Neighbourhood issues - vandalism/graffiti/other damage"
label variable NEI_05E   "Neighbourhood issues - attacks motivated by race/ethn./religion"
label variable NEI_05F   "Neighbourhood issues - people using or dealing drugs"
label variable NEI_05G   "Neighbourhood issues - people being drunk or rowdy in public"
label variable NEI_05H   "Neighbourhood issues - abandoned buildings"
label variable NEI_05I   "Neighbourhood issues - smog or air pollution"
label variable WSA_05    "Waitlist for SAH - if any household member is waitlisted"
label variable SDH_05    "Subsidized housing - ever lived in subsidized housing"
label variable CER_05    "Civic engagement - was a participant - past 12 months"
label variable CER_20    "Civic engagement - change in frequency - last 5 years"
label variable LIS_10    "Life satisfaction - subjective well-being - last 5 years"
label variable COS_10    "Community satisfaction - last 5 years"
label variable COS_15    "Community satisfaction - sense of belonging"
label variable GH_05     "General health - self-assessed health"
label variable GH_10     "General health - self-assessed mental health"
label variable REGION    "Region of residence"
label variable PMINOR    "Presence of minor (age 0-17) in household"
label variable PAGEP1    "Demographic information - age of reference person"
label variable PCER_10   "Civic engagement - number of groups - past 12 months"
label variable PCER_15   "Civic engagement - frequency - past 12 months"
label variable PCHN      "Core housing need"
label variable PCOS_05   "Community satisfaction - current sense of belonging"
label variable PDCT_05   "Tenure - owned by a household member"
label variable P1DCT_20  "Dwelling characteristics - number of bedrooms"
label variable P1DCT_25  "Dwelling characteristics - dwelling condition"
label variable PDV_SAH   "Household lives in social and affordable housing"
label variable PDV_SHCO  "Shelter costs - $ monthly amount (all costs included)"
label variable PDV_SUIT  "Classification of housing suitability"
label variable PDWLTYPE  "Dwelling type"
label variable PDWS_05   "Dwelling satisfaction - overall"
label variable PDWS_10A  "Dwelling satisfaction - having enough space"
label variable PDWS_10B  "Dwelling satisfaction - having enough bedrooms"
label variable PDWS_10C  "Dwelling satisfaction - affordability"
label variable PDWS_10D  "Dwelling satisfaction - dwelling condition"
label variable PDWS_10E  "Dwelling satisfaction - soundproofing"
label variable PDWS_10F  "Dwelling satisfaction - accessibility"
label variable PDWS_10G  "Dwelling satisfaction - safety and security within the home"
label variable PDWS_10H  "Dwelling satisfaction - energy efficiency"
label variable PDWS_10I  "Dwelling satisfaction - temperature control in winter"
label variable PDWS_10J  "Dwelling satisfaction - temperature control in summer"
label variable PEHA_05A  "Economic hardship - asked for financial help from family and friends"
label variable PEHA_05B  "Economic hardship - took on debts or sold assets"
label variable PEHA_05C  "Economic hardship - turned to charity"
label variable PEMPL     "Employment - Presence of employed person in household"
label variable PFTHB5YR  "First-time homebuyer, 5 years"
label variable PFWEIGHT  "Household weight"
label variable PHGEDUC   "Education - highest level completed (household level)"
label variable PHHSIZE   "Household size"
label variable PHHTTINC  "Total income of household"
label variable PHTYPE    "Household type"
label variable PLIS_05   "Life satisfaction - current subjective well-being"
label variable PNES_05   "Neighbourhood services - satisfaction with neighbourhood"
label variable PNSC_15   "Feeling of safety - walking alone in neighbourhood"
label variable POWN_20   "Shelter costs for owners - presence of mortgage"
label variable POWN_80   "Shelter costs for owners - $ amount currently owed on mortgage"
label variable PPAC_05   "Previous accommodations - when move to current dwelling occurred"
label variable PPAC_10   "Previous accommodations - location of previous dwelling"
label variable PPAC_23   "Previous accommodations - another person moved with respondent"
label variable PPAC_30   "Previous accommodations - tenure"
label variable PPAC_35   "Previous accommodations - rent was subsidized"
label variable PPAC_45A  "Previous accommodations - forced to move"
label variable PPAC_45C  "Previous accommodations - employment"
label variable PPAC_45D  "Previous accommodations - school"
label variable PPAC_45E  "Previous accommodations - form own household"
label variable PPAC_45F  "Previous accommodations - to be closer to family"
label variable PPAC_45G  "Previous accommodations - household size change"
label variable PPAC_45H  "Previous accommodations - reduce commuting time"
label variable PPAC_45I  "Previous accommodations - bigger/better housing"
label variable PPAC_45J  "Previous accommodations - reduce housing costs"
label variable PPAC_45K  "Previous accommodations - more desirable neighbourhood"
label variable PPAC_45L  "Previous accommodations - personal health"
label variable PPAC_45M  "Previous accommodations - become homeowner"
label variable PPAC_45N  "Previous accommodations - issue with previous landlord/tenants"
label variable PPAC_45O  "Previous accommodations - other"
label variable PPROV     "Province of residence"
label variable PRSPGNDR  "Demographic information - gender of reference person"
label variable PRSPIMST  "Main respondent's immigration status"
label variable P1SCR_05  "Shelter costs for renters - needs to report income to determine rent"
label variable PSCR_10   "Shelter costs for renters - subsidized housing"
label variable PSCR_25   "Shelter costs for renters - landlord (type)"
label variable PSCR_35   "Shelter costs for renters - dwelling from being on a waiting list"
label variable PSCR_D40  "Months spent on waitlist before obtaining subsidized housing"
label variable PSTIR_GR  "Shelter-cost-to-income ratio, groups"
label variable PVISMIN   "Demographic - Presence of a visible minority household member"
label variable PWSA_D15  "Waitlist for SAH - months currently on waitlist"
label variable P2DCT_20  "Previous dwelling characteristics - number of bedrooms"
label variable P2DCT_25  "Previous dwelling characteristics - dwelling condition"
label variable PATT_05   "Access to transportation - number of vehicles"
label variable PATT_10   "Access to transportation - availability"
label variable PATT_15A  "Access to transportation - reduce Employment/educational opportunities"
label variable PATT_15B  "Access to transportation - reduce participation in non-work activities"
label variable VERDATE   "Version date"
