label variable PUMFID    "Identificateur unique du ménage"
label variable EHA_10    "Difficultés écono. - niveau de difficulté rencontré - 12 derniers mois"
label variable EHA_25    "Difficultés écono. - omis/retardé un paiement hypothécaire/de loyer"
label variable FP_05     "Prévention des Incendies - Détecteur de fumée en état de marche"
label variable DWI_05A   "Problèmes du logement - problème de moisissures"
label variable DWI_05B   "Problèmes du logement - insectes/animaux nuisibles"
label variable DWI_05C   "Problèmes du logement - eau non potable"
label variable DWI_05D   "Problèmes du logement - mauvaise qualité de l'air intérieur"
label variable NEI_05A   "Problèmes liés au quartier - des soirées ou des voisins bruyants"
label variable NEI_05B   "Problèmes liés au quartier - des gens qui traînent dans les rues"
label variable NEI_05C   "Problèmes liés au quartier - des déchets ou des ordures qui traînent"
label variable NEI_05D   "Problèmes liés au quartier - Vandalisme/graffitis/d’autres dommages"
label variable NEI_05E   "Problème liés au quartier - attaques motivées par race/ethnie/religion"
label variable NEI_05F   "Problèmes liés au quartier - gens qui consomment ou vendent des drogue"
label variable NEI_05G   "Problèmes liés au quartier - Gens en état d’ébriété/font tapage"
label variable NEI_05H   "Problèmes liés au quartier - Des bâtiments abandonnés"
label variable NEI_05I   "Problèmes liés au quartier - le smog ou la pollution atmosphérique"
label variable WSA_05    "Liste d'attente pour LSA - si un membre du ménage est inscrit"
label variable SDH_05    "Logement subventionné - a déjà vécu dans un logement subventionné"
label variable CER_05    "Engagement communautaire - était un participant -  12 derniers mois"
label variable CER_20    "Engagement communautaire - changement de fréquence - 5 derniers ans"
label variable LIS_10    "Satisfaction à l’égard de vie - bien-être subjectif - 5 derniers ans"
label variable COS_10    "Satisfaction de votre communauté - 5 derniers ans"
label variable COS_15    "Satisfaction de votre communauté - sentiment d'appartenance"
label variable GH_05     "Santé générale - santé auto-évalué"
label variable GH_10     "Santé générale - santé mentale auto-évalué"
label variable REGION    "Région de résidence"
label variable PMINOR    ""
label variable PAGEP1    "Renseignements démographiques - âge de la personne de référence"
label variable PCER_10   "Engagement communautaire - nombre de groupes - 12 derniers mois"
label variable PCER_15   "Engagement communautaire - fréquence - 12 derniers mois"
label variable PCHN      "Besoin impérieux en matière de logement"
label variable PCOS_05   "Satisfaction de votre communauté - sentiment d'appartenance à présent"
label variable PDCT_05   "Mode d’occupation - membre du ménage propriétaire"
label variable P1DCT_20  "Caractéristiques du logement - nombre de chambres à coucher"
label variable P1DCT_25  "Caractéristiques du logement - état du logement"
label variable PDV_SAH   "Le ménage vit dans un logement social et abordable"
label variable PDV_SHCO  "Coût de logement - $ montant mensuel (comptant tous les frais)"
label variable PDV_SUIT  "Classification de taille convenable du logement"
label variable PDWLTYPE  "Type de logement"
label variable PDWS_05   "Satisfaction du logement - en général"
label variable PDWS_10A  "Satisfaction du logement - superficie totale"
label variable PDWS_10B  "Satisfaction du logement - nombre de chambres à coucher"
label variable PDWS_10C  "Satisfaction du logement - prix abordable"
label variable PDWS_10D  "Satisfaction du logement - état du logement"
label variable PDWS_10E  "Satisfaction du logement - atténuation des bruits"
label variable PDWS_10F  "Satisfaction du logement - accessibilité"
label variable PDWS_10G  "Satisfaction du logement - sécurité chez soi"
label variable PDWS_10H  "Satisfaction du logement - efficacité énergétique"
label variable PDWS_10I  "Satisfaction du logement - régulation de température en hiver"
label variable PDWS_10J  "Satisfaction du logement - régulation de température en été"
label variable PEHA_05A  "Difficultés écono. - a demandé de l'aide à la famille/à des amis"
label variable PEHA_05B  "Difficultés écono. - s'est endetté ou a vendu un bien"
label variable PEHA_05C  "Difficultés écono. - a fait appel à un organisme de bienfaisance"
label variable PEMPL     "Emploi - indicateur qu'un membre du ménage possède un emploi"
label variable PFTHB5YR  "Accédant à la propriété, 5 années"
label variable PFWEIGHT  "Poids du ménage"
label variable PHGEDUC   "Éducation - plus haut niveau de scolarité (niveau ménage)"
label variable PHHSIZE   "Taille du ménage"
label variable PHHTTINC  "Revenu total du ménage"
label variable PHTYPE    "Type du ménage"
label variable PLIS_05   "Satisfaction à l'égard de la vie - bien-être subjectif à présent"
label variable PNES_05   "Besoins en services - satisfaction du quartier"
label variable PNSC_15   "Sentiment de sécurité - marcher seul dans le quartier"
label variable POWN_20   "Frais des propriétaires - présence d'une hypothèque sur le logement"
label variable POWN_80   "Frais des propriétaires - $ montant dû actuellement sur l'hypothèque"
label variable PPAC_05   "Logement précédent - quand emménagement dans logement actuel a eu lieu"
label variable PPAC_10   "Logement précédent - endroit du logement précédent"
label variable PPAC_23   "Logement précédent - une autre personne a déménagé avec le répondant"
label variable PPAC_30   "Logement précédent - mode d'occupation"
label variable PPAC_35   "Logement précédent - le loyer était subventionné"
label variable PPAC_45A  "Logement précédent - était obligé de déménager"
label variable PPAC_45C  "Logement précédent - emploi"
label variable PPAC_45D  "Logement précédent - école"
label variable PPAC_45E  "Logement précédent - fonder son propre ménage"
label variable PPAC_45F  "Logement précédent - pour être plus près de la famille"
label variable PPAC_45G  "Logement précédent - changement de la taille du ménage"
label variable PPAC_45H  "Logement précédent - réduire la durée en déplacements quotidiens"
label variable PPAC_45I  "Logement précédent - logement plus grand ou de qualité supérieure"
label variable PPAC_45J  "Logement précédent - réduire les coûts de logement"
label variable PPAC_45K  "Logement précédent - pour un quartier plus agréable"
label variable PPAC_45L  "Logement précédent - problèmes de santé personnels"
label variable PPAC_45M  "Logement précédent - devenir propriétaire"
label variable PPAC_45N  "Logement précédent -problèmes avec le propriétaire précédent/locataire"
label variable PPAC_45O  "Logement précédent - autre"
label variable PPROV     "Province de résidence"
label variable PRSPGNDR  "Renseignements démographiques - genre de la personne de référence"
label variable PRSPIMST  "Statut d’immigration du répondant principal"
label variable P1SCR_05  "Frais des locataires - doit déclarer revenu pour déterminer le loyer"
label variable PSCR_10   "Frais des locataires - logement subventionné"
label variable PSCR_25   "Frais des locataires - propriétaire (type)"
label variable PSCR_35   "Frais des locataires - logement après inscrit sur une liste d’attente"
label variable PSCR_D40  "Nombre de mois sur la liste d'attente pour ce logement subventionné"
label variable PSTIR_GR  "Rapport des frais de logement au revenu, groupes"
label variable PVISMIN   "Démographie - Indicateur d’une minorité visible dans le ménage"
label variable PWSA_D15  "Liste d'attente de LSA - nombre de mois en attente courant"
label variable P2DCT_20  "Caractéristiques du logement précédent - nombre de chambres à coucher"
label variable P2DCT_25  "Caractéristiques du logement précédent - état du logement"
label variable PATT_05   "Accès au transport - nombre de véhicules"
label variable PATT_10   "Accès au transport - disponibilité"
label variable PATT_15A  "Accès au transport - reduit possibilités d’emploi/ d’éducation"
label variable PATT_15B  "Accès au transport - reduit participation non-liées au travail"
label variable VERDATE   "Date de la version"
