label values   CER_05    CER_05_FMT
label values   CER_20    CER_20_FMT
label values   COS_10    COS_10_FMT
label values   COS_15    COS_15_FMT
label values   DWI_05A   DWI_05A_FMT
label values   DWI_05B   DWI_05B_FMT
label values   DWI_05C   DWI_05C_FMT
label values   DWI_05D   DWI_05D_FMT
label values   EHA_10    EHA_10_FMT
label values   EHA_25    EHA_25_FMT
label values   FP_05     FP_05_FMT
label values   GH_05     GH_05_FMT
label values   GH_10     GH_10_FMT
label values   LIS_10    LIS_10_FMT
label values   NEI_05A   NEI_05A_FMT
label values   NEI_05B   NEI_05B_FMT
label values   NEI_05C   NEI_05C_FMT
label values   NEI_05D   NEI_05D_FMT
label values   NEI_05E   NEI_05E_FMT
label values   NEI_05F   NEI_05F_FMT
label values   NEI_05G   NEI_05G_FMT
label values   NEI_05H   NEI_05H_FMT
label values   NEI_05I   NEI_05I_FMT
label values   P1DCT_20  P1DCT_20_FMT
label values   P1DCT_25  P1DCT_25_FMT
label values   P1SCR_05  P1SCR_05_FMT
label values   P2DCT_20  P2DCT_20_FMT
label values   P2DCT_25  P2DCT_25_FMT
label values   PAGEP1    PAGEP1_FMT
label values   PATT_05   PATT_05_FMT
label values   PATT_10   PATT_10_FMT
label values   PATT_15A  PATT_15A_FMT
label values   PATT_15B  PATT_15B_FMT
label values   PCER_10   PCER_10_FMT
label values   PCER_15   PCER_15_FMT
label values   PCHN      PCHN_FMT
label values   PCOS_05   PCOS_05_FMT
label values   PDCT_05   PDCT_05_FMT
label values   PDV_SAH   PDV_SAH_FMT
label values   PDV_SUIT  PDV_SUIT_FMT
label values   PDWS_05   PDWS_05_FMT
label values   PDWS_10A  PDWS_10A_FMT
label values   PDWS_10B  PDWS_10B_FMT
label values   PDWS_10C  PDWS_10C_FMT
label values   PDWS_10D  PDWS_10D_FMT
label values   PDWS_10E  PDWS_10E_FMT
label values   PDWS_10F  PDWS_10F_FMT
label values   PDWS_10G  PDWS_10G_FMT
label values   PDWS_10H  PDWS_10H_FMT
label values   PDWS_10I  PDWS_10I_FMT
label values   PDWS_10J  PDWS_10J_FMT
label values   PEHA_05A  PEHA_05A_FMT
label values   PEHA_05B  PEHA_05B_FMT
label values   PEHA_05C  PEHA_05C_FMT
label values   PEMPL     PEMPL_FMT
label values   PFTHB5YR  PFTHB5YR_FMT
label values   PHGEDUC   PHGEDUC_FMT
label values   PHHSIZE   PHHSIZE_FMT
label values   PHHTTINC  PHHTTINC_FMT
label values   PLIS_05   PLIS_05_FMT
label values   PMINOR    PMINOR_FMT
label values   PNES_05   PNES_05_FMT
label values   PNSC_15   PNSC_15_FMT
label values   POWN_20   POWN_20_FMT
label values   POWN_80   POWN_80_FMT
label values   PPAC_05   PPAC_05_FMT
label values   PPAC_10   PPAC_10_FMT
label values   PPAC_23   PPAC_23_FMT
label values   PPAC_30   PPAC_30_FMT
label values   PPAC_35   PPAC_35_FMT
label values   PPAC_45A  PPAC_45A_FMT
label values   PPAC_45C  PPAC_45C_FMT
label values   PPAC_45D  PPAC_45D_FMT
label values   PPAC_45E  PPAC_45E_FMT
label values   PPAC_45F  PPAC_45F_FMT
label values   PPAC_45G  PPAC_45G_FMT
label values   PPAC_45H  PPAC_45H_FMT
label values   PPAC_45I  PPAC_45I_FMT
label values   PPAC_45J  PPAC_45J_FMT
label values   PPAC_45K  PPAC_45K_FMT
label values   PPAC_45L  PPAC_45L_FMT
label values   PPAC_45M  PPAC_45M_FMT
label values   PPAC_45N  PPAC_45N_FMT
label values   PPAC_45O  PPAC_45O_FMT
label values   PRSPGNDR  PRSPGNDR_FMT
label values   PRSPIMST  PRSPIMST_FMT
label values   PSCR_10   PSCR_10_FMT
label values   PSCR_25   PSCR_25_FMT
label values   PSCR_35   PSCR_35_FMT
label values   PSTIR_GR  PSTIR_GR_FMT
label values   PVISMIN   PVISMIN_FMT
label values   SDH_05    SDH_05_FMT
label values   WSA_05    WSA_05_FMT
