VALUE LABELS
              /CER_05 DWI_05A DWI_05B DWI_05C DWI_05D EHA_25 FP_05 P1SCR_05 PDCT_05 PDV_SAH PEHA_05A PEHA_05B PEHA_05C
               POWN_20 PPAC_23 PPAC_35 PPAC_45A PPAC_45C PPAC_45D PPAC_45E PPAC_45F PPAC_45G PPAC_45H PPAC_45I PPAC_45J
               PPAC_45K PPAC_45L PPAC_45M PPAC_45N PPAC_45O PSCR_10 PSCR_35 SDH_05 WSA_05
                    1   "Oui"
                    2   "Non"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /CER_20 COS_10 LIS_10
                    1   "Augmenté"
                    2   "Diminué"
                    3   "Demeuré à peu près le même"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /COS_15
                    1   "Très fort"
                    2   "Plus ou moins fort"
                    3   "Plus ou moins faible"
                    4   "Très faible"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /EHA_10
                    1   "Très difficile"
                    2   "Difficile"
                    3   "Ni difficile ni facile"
                    4   "Facile"
                    5   "Très facile"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /GH_05 GH_10
                    1   "Excellente"
                    2   "Très bonne"
                    3   "Bonne"
                    4   "Passable"
                    5   "Mauvaise"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /NEI_05A NEI_05B NEI_05C NEI_05D NEI_05E NEI_05F NEI_05G NEI_05H NEI_05I
                    1   "Un gros problème"
                    2   "Un problème modéré"
                    3   "Un petit problème"
                    4   "Pas du tout un problème"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /P1DCT_20
                   01   "Une ou moins"
                   02   "Deux"
                   03   "Trois"
                   04   "Quatre ou plus"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /P1DCT_25 P2DCT_25
                    1   "Non, seulement un entretien régulier..."
                    2   "Oui, des réparations mineures..."
                    3   "Oui, des réparations majeures..."
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /P2DCT_20
                  001   "Une ou moins"
                  002   "Deux"
                  003   "Trois"
                  004   "Quatre ou plus"
                  996   "Enchaînement valide"
                  997   "Ne sait pas"
                  998   "Refus"
                  999   "Non déclaré"
              /PAGEP1
                    1   "29 ans et moins"
                    2   "30-44 ans"
                    3   "45-64 ans"
                    4   "65 ans et plus"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PATT_05
                   00   ""
                   01   ""
                   02   ""
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PATT_10
                    1   "Tout le temps"
                    2   "De temps en temps"
                    3   "Rarement"
                    4   "Jamais"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PATT_15A
                    1   "Énormément ou Beaucoup"
                    2   "Quelque peu ou Trés peu"
                    3   "Pas du tout"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PATT_15B
                    1   "Énormément ou Beaucoup"
                    2   "Quelque peu"
                    3   "Très peu"
                    4   "Pas du tout"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PCER_10
                   01   "Un"
                   02   "Deux ou plus"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PCER_15
                    1   "Au moins une fois par semaine"
                    2   "Quelques fois par mois"
                    3   "Une fois par mois"
                    4   "1 ou 2 fois par année ou pas au cours de la dernière année"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PCHN
                    1   "Ayant des besoins impérieux en matière de logement"
                    2   "N'ayant pas des besoins impérieux en matière de logement"
                    3   "Non examiné pour les besoins impérieux"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PCOS_05 PLIS_05
                   01   "0 - Très insatisfait, 1, 2"
                   02   "3"
                   03   "4"
                   04   "5"
                   05   "6"
                   06   "7"
                   07   "8"
                   08   "9"
                   09   "10 - Très satisfait"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PDV_SHCO
           9999999.96   "Enchaînement valide"
           9999999.97   "Ne sait pas"
           9999999.98   "Refus"
           9999999.99   "Non déclaré"
              /PDV_SUIT
                    1   "Taille suffisante"
                    2   "Taille insuffisante"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PDWLTYPE
                 "00"   "Logement collectif"
                 "01"   "Maison individuelle non attenante"
                 "02"   "Maison jumelée ou autre maison individuelle attenante"
                 "03"   "Maison en rangée"
                 "04"   "Appartement ou plain-pied dans un duplex"
                 "05"   "Appartement dans un immeuble de cinq étages ou plus"
                 "06"   "Appartement dans un immeuble de moins de cinq étages"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /PDWS_05 PNES_05
                    1   "0 - Très insatisfait, 1, 2, 3, 4, 5"
                    2   "6, 7"
                    3   "8, 9, 10 - Très satisfait"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PDWS_10A PDWS_10B PDWS_10C PDWS_10D PDWS_10E PDWS_10F PDWS_10G PDWS_10H PDWS_10I PDWS_10J
                    1   "Très satisfait"
                    2   "Satisfait"
                    3   "Ni satisfait ni insatisfait"
                    4   "Insatisfait ou très insatisfait"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PEMPL
                    1   "Au moins un membre du ménage possède un emploi"
                    2   "Aucun membre du ménage possède un emploi"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PFTHB5YR
                    1   "Accédant à la propriété, 5 années"
                    2   "Pas un accédant à la propriété, 5 années"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PHGEDUC
                   01   "Niveau inférieur à un diplôme d’études secondaires"
                   02   "Diplôme d’études secondaires ou un certificat d’équivalence"
                   03   "Certificat ou diplôme d’une école de  métiers"
                   04   "Certificat ou diplôme d’un collège, d’un cégep"
                   05   "Grade universitaire au-dessous du baccalauréat"
                   06   "Baccalauréat"
                   07   "Grade universitaire au-dessus du baccalauréat"
                   08   "Grade universitaire (T.N.-O.)"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PHHSIZE
                   01   "1"
                   02   "2"
                   03   "3"
                   04   "4"
                   05   "5+"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PHHTTINC
          99999999996   "Enchaînement valide"
          99999999997   "Ne sait pas"
          99999999998   "Refus"
          99999999999   "Non déclaré"
              /PHTYPE
                 "01"   "Un couple (marié ou en union libre) avec des enfants"
                 "02"   "Un couple (marié ou en union libre) sans enfant"
                 "03"   "Une famille monoparentale"
                 "04"   "Une famille de recensement plus des personnes additionnelles"
                 "05"   "Personne seule (hors famille de recensement)"
                 "06"   "Deux personnes ou plus qui sont hors famille de recensement"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /PMINOR
                    1   ""
                    2   ""
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PNSC_15
                    1   "Tout à fait en sécurité"
                    2   "Plutôt en sécurité"
                    3   "Pas en sécurité"
                    4   "Ne marche jamais seul(e)"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /POWN_80
             99999996   "Enchaînement valide"
             99999997   "Ne sait pas"
             99999998   "Refus"
             99999999   "Non déclaré"
              /PPAC_05
                   01   "Moins de 2 ans"
                   02   "De 2 ans à moins de 5 ans"
                   03   "De 5 ans à moins de 10 ans"
                   04   "10 ans et plus + Toujours vécu dans ce logement"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PPAC_10
                    1   "Dans la/le même ville/village/canton .../réserve indienne"
                    2   "Autre ville...,/réserve indienne ou à l’extérieur du Canada"
                    3   "À l’extérieur du Canada"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PPAC_30
                    1   "Propriétaire ou copropriétaire"
                    2   "Locataire"
                    3   "Logé gratuitement"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PPROV
                 "10"   "Terre-Neuve-et-Labrador"
                 "11"   "Île-du-Prince-Édouard"
                 "12"   "Nouvelle-Écosse"
                 "13"   "Nouveau-Brunswick"
                 "24"   "Québec"
                 "35"   "Ontario"
                 "46"   "Manitoba"
                 "47"   "Saskatchewan"
                 "48"   "Alberta"
                 "59"   "Colombie-Britannique"
                 "60"   "Yukon"
                 "61"   "Territoires du Nord-Ouest"
                 "62"   "Nunavut"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /PRSPGNDR
                    1   "Masculin"
                    2   "Féminin"
                    3   "Ou veuillez préciser"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PRSPIMST
                    1   "Non-immigré (citoyens nés au Canada)"
                    2   "Immigré + Résidents non permanent"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PSCR_25
                   01   "Coopérative d’habitation ou organisme sans but lucratif"
                   02   "Un gouvernement"
                   03   "Une entreprise privée ou un particulier"
                   04   "Un membre de la famille, un employeur ou autre"
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /PSCR_D40 PWSA_D15
                999.6   "Enchaînement valide"
                999.7   "Ne sait pas"
                999.8   "Refus"
                999.9   "Non déclaré"
              /PSTIR_GR
                    1   "Moins de 30% du revenu est consacré aux frais de logement"
                    2   "De 30% à moins de 50% du revenu est consacré aux frais"
                    3   "De 50% à moins de 100% du revenu est consacré aux frais"
                    4   "100% ou plus du revenu est consacré aux frais de logements"
                    5   "Sans objet"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /PVISMIN
                    1   "Au moins un membre du ménage est une minorité visible"
                    2   "Aucun membre du ménage est une minorité visible"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /REGION
                 "01"   "Atlantique"
                 "02"   "Québec"
                 "03"   "Ontario"
                 "04"   "Prairies"
                 "05"   "Colombie-Britannique"
                 "06"   "Territoires"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /VERDATE
         "9999999996"   "Enchaînement valide"
         "9999999997"   "Ne sait pas"
         "9999999998"   "Refus"
         "9999999999"   "Non déclaré"
    .
 
